name: GitHub CI

on: [ push, pull_request ]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17, 21 ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Set up Maven
        run: mvn --errors --batch-mode --show-version wrapper:wrapper -Dmaven="3.9.9"

      - name: Build with Maven
        run: ./mvnw clean install -e -B -V -fae
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

